import { TrayConfig } from './types';

export const TRAYS: TrayConfig[] = [
  {
    tag: 'AI工具',
    color: '#E0F2F1', // Mint Green
    bgColor: 'bg-[#E0F2F1]/30',
  },
  {
    tag: '个人成长',
    color: '#FFF9C4', // Cream Yellow
    bgColor: 'bg-[#FFF9C4]/30',
  },
  {
    tag: 'AI短剧',
    color: '#FCE4EC', // Sakura Pink
    bgColor: 'bg-[#FCE4EC]/30',
  },
  {
    tag: 'Vibecoding',
    color: '#F3E5F5', // Lavender
    bgColor: 'bg-[#F3E5F5]/30',
  },
  {
    tag: '自媒体',
    color: '#E3F2FD', // Sky Blue
    bgColor: 'bg-[#E3F2FD]/30',
  },
  {
    tag: '其他',
    color: '#F5F5F5', // Light Gray
    bgColor: 'bg-[#F5F5F5]/30',
  },
];

export const MOCK_CARDS: any[] = [
  {
    id: '1',
    title: 'Cursor + Claude 3.5: The Future of Vibecoding',
    url: 'https://example.com/1',
    summary: 'Explores how natural language is becoming the primary interface for software development, enabling rapid prototyping through "vibes".',
    level: 4,
    tags: ['Vibecoding', 'AI工具'],
    likes: 124,
    comments: 45,
    createdAt: '2024-03-01',
  },
  {
    id: '2',
    title: 'Mastering the Pomodoro Technique for Deep Work',
    url: 'https://example.com/2',
    summary: 'A deep dive into time-blocking strategies that enhance focus and prevent burnout during long coding sessions.',
    level: 2,
    tags: ['个人成长'],
    likes: 89,
    comments: 12,
    createdAt: '2024-03-02',
  },
  {
    id: '3',
    title: 'AI-Generated Short Films: A New Era of Storytelling',
    url: 'https://example.com/3',
    summary: 'How generative video tools like Sora and Runway are democratizing film production for independent creators.',
    level: 3,
    tags: ['AI短剧'],
    likes: 256,
    comments: 67,
    createdAt: '2024-03-03',
  },
  {
    id: '4',
    title: 'Top 10 AI Productivity Tools for 2024',
    url: 'https://example.com/4',
    summary: 'A curated list of the most impactful AI tools for automating repetitive tasks and boosting creative output.',
    level: 1,
    tags: ['AI工具'],
    likes: 432,
    comments: 89,
    createdAt: '2024-03-04',
  },
  {
    id: '5',
    title: 'The Psychology of Habit Formation',
    url: 'https://example.com/5',
    summary: 'Understanding the neurological loops that drive our daily routines and how to rewire them for success.',
    level: 5,
    tags: ['个人成长'],
    likes: 156,
    comments: 34,
    createdAt: '2024-03-05',
  },
  {
    id: '6',
    title: 'Vibecoding: Why Syntax Doesn\'t Matter Anymore',
    url: 'https://example.com/6',
    summary: 'A provocative look at how LLMs are shifting the developer\'s role from writing code to orchestrating intent.',
    level: 3,
    tags: ['Vibecoding'],
    likes: 178,
    comments: 56,
    createdAt: '2024-03-06',
  },
  {
    id: '7',
    title: 'Scriptwriting for AI Short Dramas',
    url: 'https://example.com/7',
    summary: 'Techniques for crafting compelling narratives specifically designed for short-form vertical video platforms.',
    level: 4,
    tags: ['AI短剧'],
    likes: 92,
    comments: 21,
    createdAt: '2024-03-07',
  },
  {
    id: '8',
    title: 'Building a Second Brain with AI',
    url: 'https://example.com/8',
    summary: 'Leveraging AI to organize personal knowledge and create a searchable digital archive of your thoughts.',
    level: 2,
    tags: ['AI工具', '个人成长'],
    likes: 312,
    comments: 78,
    createdAt: '2024-03-08',
  },
  {
    id: '9',
    title: 'The Rise of Vertical Cinema',
    url: 'https://example.com/9',
    summary: 'Analyzing the aesthetic and structural shifts required when moving from traditional widescreen to mobile-first video.',
    level: 2,
    tags: ['AI短剧'],
    likes: 145,
    comments: 32,
    createdAt: '2024-03-09',
  },
  {
    id: '10',
    title: 'LLM Fine-tuning for Personal Workflows',
    url: 'https://example.com/10',
    summary: 'A technical guide to customizing large language models to better understand your specific domain and style.',
    level: 5,
    tags: ['AI工具', 'Vibecoding'],
    likes: 204,
    comments: 41,
    createdAt: '2024-03-10',
  },
  {
    id: '11',
    title: '自媒体运营实战指南',
    url: 'https://example.com/11',
    summary: '从零开始打造个人 IP，掌握流量密码，实现自媒体变现的完整路径。',
    level: 3,
    tags: ['自媒体'],
    likes: 567,
    comments: 123,
    createdAt: '2024-03-11',
  },
  {
    id: '12',
    title: '如何写出爆款小红书文案',
    url: 'https://example.com/12',
    summary: '拆解小红书热门笔记的底层逻辑，教你如何利用情绪价值和视觉冲击力吸引粉丝。',
    level: 2,
    tags: ['自媒体'],
    likes: 890,
    comments: 234,
    createdAt: '2024-03-12',
  },
  {
    id: '13',
    title: '2024 视频剪辑软件大比拼',
    url: 'https://example.com/13',
    summary: '对比剪映、PR、Final Cut Pro 等主流剪辑工具，找到最适合你的那一款。',
    level: 1,
    tags: ['自媒体', 'AI工具'],
    likes: 345,
    comments: 67,
    createdAt: '2024-03-13',
  },
  {
    id: '14',
    title: '生活中的冷知识：为什么天空是蓝色的',
    url: 'https://example.com/14',
    summary: '瑞利散射原理的通俗解释，让你在闲聊中也能展现博学的一面。',
    level: 1,
    tags: ['其他'],
    likes: 123,
    comments: 23,
    createdAt: '2024-03-14',
  },
  {
    id: '15',
    title: '如何挑选一把好的人体工学椅',
    url: 'https://example.com/15',
    summary: '保护腰椎，从选对椅子开始。详细解析人体工学椅的各项参数。',
    level: 2,
    tags: ['其他'],
    likes: 456,
    comments: 89,
    createdAt: '2024-03-15',
  },
  {
    id: '16',
    title: 'AI 绘画：Midjourney 进阶教程',
    url: 'https://example.com/16',
    summary: '掌握复杂的 Prompt 技巧，生成电影级质感的艺术作品。',
    level: 4,
    tags: ['AI工具'],
    likes: 678,
    comments: 156,
    createdAt: '2024-03-16',
  },
  {
    id: '17',
    title: '深度学习入门：神经网络基础',
    url: 'https://example.com/17',
    summary: '从数学原理到代码实现，带你揭开深度学习的神秘面纱。',
    level: 5,
    tags: ['AI工具'],
    likes: 234,
    comments: 45,
    createdAt: '2024-03-17',
  },
  {
    id: '18',
    title: '高效学习法：费曼技巧实践',
    url: 'https://example.com/18',
    summary: '教是最好的学。通过向他人解释来巩固自己的知识体系。',
    level: 3,
    tags: ['个人成长'],
    likes: 789,
    comments: 167,
    createdAt: '2024-03-18',
  },
  {
    id: '19',
    title: '短视频脚本创作的黄金法则',
    url: 'https://example.com/19',
    summary: '3秒抓人，10秒反转。掌握短视频脚本的核心节奏。',
    level: 4,
    tags: ['自媒体', 'AI短剧'],
    likes: 432,
    comments: 98,
    createdAt: '2024-03-19',
  },
  {
    id: '20',
    title: '如何克服拖延症：微习惯的力量',
    url: 'https://example.com/20',
    summary: '从每天做一个俯卧撑开始，通过微小的改变撬动巨大的进步。',
    level: 2,
    tags: ['个人成长'],
    likes: 901,
    comments: 212,
    createdAt: '2024-03-20',
  },
];

